---
- hosts: new
  tasks:
  - name: cp package
    copy: src=pkg/telegraf-0.11.1-1.x86_64.rpm dest=/root
  - name: install telegraf
    shell: yum localinstall telegraf-0.11.1-1.x86_64.rpm -y
  - name: cp sricpts
    copy: src=scripts/monitor_telegraf.sh dest=/root/ backup=no mode=0755
  - name: monitor_process by cron
    cron: name="monitor telegraf" minute="*/5" job="/root/monitor_telegraf.sh 2&>1 >> /root/monitor.log" state="present"
  - name: config
    template: src=conf/telegraf.conf dest=/etc/telegraf/telegraf.conf backup=yes
    notify:
        restart telegraf
  handlers:
  - name: restart telegraf
    service: name=telegraf state=restarted

